# Generated by Django 4.2.5 on 2024-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('club_description', models.TextField()),
                ('club_logo', models.ImageField(upload_to='clubs/')),
            ],
        ),
    ]
